In [2]:
from sqlalchemy import create_engine
import pandas as pd

In [4]:
 # connect with postgresql
from sqlalchemy import create_engine
import pandas as pd

username = "postgres"
password = "postgreSQL"
host = "localhost"
port = 5432
database = "Construction"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [5]:
query = "SELECT * FROM construction_data"

data = pd.read_sql(query, engine)

In [6]:
data.head(10)

,project_id,project_name,project_type,region,location,contractor,start_date,planned_end_date,actual_end_date,planned_cost_inr,...,quality_rating,safety_score,delay_days,project_status,actual_duration_day,planned_duration,total_direct_cost,cost_overrun,progress_variance,cost_overrun_pct
0,P1503,Metro Project 0503,Metro,South,Chennai,ABC Infra,2024-11-16,2026-05-08,2026-06-20,1.455362e+09,...,83.2,63.7,43,Delayed,581,538,1.631524e+09,176162137.0,-8.1,12.10
1,P1010,Metro Project 0010,Metro,South,Bengaluru,Apex Contractors,2023-05-02,2023-10-15,2024-01-20,2.937749e+09,...,87.2,96.2,97,Delayed,263,166,3.287138e+09,349389197.0,-93.1,11.89
2,P2362,Metro Project 1362,Metro,West,Pune,ABC Infra,2024-07-03,2025-07-23,2025-09-02,1.159097e+09,...,83.8,96.0,41,Delayed,426,385,1.260684e+09,101587431.0,-2.9,8.76
3,P1011,Power Transmission Project 0011,Power Transmission,West,Ahmedabad,Vertex Infra,2024-04-11,2025-06-28,2025-10-13,6.657122e+08,...,69.7,94.6,107,Delayed,550,443,7.122142e+08,46502031.0,-19.5,6.99
4,P1012,Power Transmission Project 0012,Power Transmission,Central,Nagpur,BuildTech,2023-08-03,2025-10-15,2025-11-26,7.220004e+08,...,76.1,95.4,42,Delayed,846,804,8.069665e+08,84966120.0,-10.6,11.77
5,P1013,Building Project 0013,Building,South,Chennai,BuildTech,2023-11-27,2024-08-02,2024-10-05,8.726266e+08,...,79.6,77.1,64,Delayed,313,249,9.777465e+08,105119908.0,-11.9,12.05
6,P1014,Bridge Project 0014,Bridge,South,Bengaluru,ABC Infra,2024-04-03,2025-09-15,2025-10-31,6.450056e+08,...,88.1,88.6,46,Delayed,576,530,7.067069e+08,61701256.0,-7.5,9.57
7,P1015,Bridge Project 0015,Bridge,South,Bengaluru,MegaBuild,2023-03-29,2023-10-29,2023-12-12,5.645487e+08,...,93.7,100.0,44,Delayed,258,214,5.878910e+08,23342317.0,-12.4,4.13
8,P1016,Metro Project 0016,Metro,North,Delhi,MegaBuild,2024-01-08,2026-01-23,2026-02-18,1.067937e+09,...,83.0,100.0,26,Completed,772,746,1.127711e+09,59774618.0,-1.5,5.60
9,P1017,Power Transmission Project 0017,Power Transmission,Central,Nagpur,Shakti Engineering,2023-04-10,2025-08-31,2025-11-25,6.314345e+08,...,83.7,86.7,86,Delayed,960,874,7.548005e+08,123366025.0,-15.4,19.54

In [7]:
data.shape

(1515, 32)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515 entries, 0 to 1514
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   project_id            1515 non-null   object
 1   project_name          1515 non-null   object
 2   project_type          1515 non-null   object
 3   region                1515 non-null   object
 4   location              1515 non-null   object
 5   contractor            1515 non-null   object
 6   start_date            1515 non-null   object
 7   planned_end_date      1515 non-null   object
 8   actual_end_date       1515 non-null   object
 9   planned_cost_inr      1515 non-null   float64
 10  actual_cost_inr       1515 non-null   float64
 11  planned_progress_pct  1515 non-null   float64
 12  actual_progress_pct   1503 non-null   float64
 13  manpower              1515 non-null   int64
 14  material_cost_inr     1506 non-null   float64
 15  labor_cost_inr        1515 non-null   float64
 16  equipment_cost_inr    1515 non-null   float64
 17  equipment_hours       1515 non-null   float64
 18  safety_incidents      1515 non-null   int64
 19  quality_issues        1515 non-null   int64
 20  weather_delay_days    1515 non-null   int64
 21  design_changes        1515 non-null   int64
 22  quality_rating        1515 non-null   float64
 23  safety_score          1515 non-null   float64
 24  delay_days            1515 non-null   int64
 25  project_status        1515 non-null   object
 26  actual_duration_day   1515 non-null   int64
 27  planned_duration      1515 non-null   int64
 28  total_direct_cost     1515 non-null   float64
 29  cost_overrun          1515 non-null   float64
 30  progress_variance     1515 non-null   float64
 31  cost_overrun_pct      1515 non-null   float64
dtypes: float64(14), int64(8), object(10)
memory usage: 378.9+ KB

In [10]:
data.isnull().sum()

project_id               0
project_name             0
project_type             0
region                   0
location                 0
contractor               0
start_date               0
planned_end_date         0
actual_end_date          0
planned_cost_inr         0
actual_cost_inr          0
planned_progress_pct     0
actual_progress_pct     12
manpower                 0
material_cost_inr        9
labor_cost_inr           0
equipment_cost_inr       0
equipment_hours          0
safety_incidents         0
quality_issues           0
weather_delay_days       0
design_changes           0
quality_rating           0
safety_score             0
delay_days               0
project_status           0
actual_duration_day      0
planned_duration         0
total_direct_cost        0
cost_overrun             0
progress_variance        0
cost_overrun_pct         0
dtype: int64

In [12]:
data.duplicated()
data.duplicated().sum()  # 15 rows duplicated

0       False
1       False
2       False
3       False
4       False
        ...
1510     True
1511     True
1512     True
1513     True
1514     True
Length: 1515, dtype: bool

In [13]:
data.tail(5)

,project_id,project_name,project_type,region,location,contractor,start_date,planned_end_date,actual_end_date,planned_cost_inr,...,quality_rating,safety_score,delay_days,project_status,actual_duration_day,planned_duration,total_direct_cost,cost_overrun,progress_variance,cost_overrun_pct
1510,P2133,Highway Project 1133,Highway,West,Pune,MegaBuild,2025-02-12,2026-05-27,2026-08-05,1.505521e+09,...,84.3,95.1,70,Delayed,539,469,1.635896e+09,130375151.0,-13.4,8.66
1511,P1417,Power Transmission Project 0417,Power Transmission,North,Jaipur,Apex Contractors,2024-08-02,2025-05-18,2025-07-12,1.323358e+09,...,85.1,98.7,55,Delayed,344,289,1.430963e+09,107604222.0,-14.0,8.13
1512,P1718,Metro Project 0718,Metro,South,Bengaluru,MegaBuild,2024-08-29,2026-06-06,2026-09-21,1.132982e+09,...,70.3,98.7,107,Delayed,753,646,1.301765e+09,168782838.0,-21.9,14.90
1513,P1979,Power Transmission Project 0979,Power Transmission,Central,Nagpur,MegaBuild,2024-12-24,2025-11-25,2026-01-01,1.270351e+09,...,74.7,98.8,37,Delayed,373,336,1.304798e+09,34446436.0,-5.3,2.71
1514,P1836,Water Infrastructure Project 0836,Water Infrastructure,Central,Indore,UrbanWorks,2023-03-15,2025-02-25,2025-03-23,8.610880e+08,...,79.8,86.0,26,On Track,739,713,9.760362e+08,114948192.0,-2.2,13.35

In [14]:
data = data.drop_duplicates()

In [15]:
data.shape

(1500, 32)

In [18]:
data.describe()

,planned_cost_inr,actual_cost_inr,planned_progress_pct,actual_progress_pct,manpower,material_cost_inr,labor_cost_inr,equipment_cost_inr,equipment_hours,safety_incidents,...,design_changes,quality_rating,safety_score,delay_days,actual_duration_day,planned_duration,total_direct_cost,cost_overrun,progress_variance,cost_overrun_pct
count,1.500000e+03,1.500000e+03,1500.000000,1488.000000,1500.000000,1.491000e+03,1.500000e+03,1.500000e+03,1500.000000,1500.000000,...,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1.500000e+03,1.500000e+03,1500.000000,1500.000000
mean,1.075014e+09,1.168646e+09,90.086000,80.850067,408.996000,6.568349e+08,2.895357e+08,2.237734e+08,6165.869333,1.250667,...,2.087333,84.182600,90.684867,49.290000,556.259333,506.969333,1.166203e+09,9.363203e+07,-9.882733,8.646887
std,5.380576e+08,5.893202e+08,3.916829,6.057746,238.089413,3.346853e+08,1.504383e+08,1.396299e+08,3416.755699,1.138140,...,1.518303,9.217468,8.298578,27.293318,228.819822,226.666195,5.918827e+08,7.059561e+07,10.258232,4.430913
min,3.088605e+08,3.156725e+08,78.000000,57.700000,80.000000,1.736877e+08,6.532713e+07,3.913505e+07,300.000000,0.000000,...,0.000000,50.000000,57.000000,-10.000000,119.000000,120.000000,1.479898e+08,-1.250505e+08,-93.900000,-7.070000
25%,6.899201e+08,7.548699e+08,87.400000,76.800000,243.000000,4.194083e+08,1.826104e+08,1.264114e+08,3212.250000,0.000000,...,1.000000,78.200000,85.775000,30.000000,358.000000,308.500000,7.526882e+08,4.460691e+07,-14.125000,5.730000
50%,9.454890e+08,1.029201e+09,90.100000,80.800000,355.000000,5.742554e+08,2.554080e+08,1.851726e+08,6170.500000,1.000000,...,2.000000,84.700000,92.200000,49.000000,554.000000,499.500000,1.028866e+09,7.876218e+07,-9.400000,8.580000
75%,1.339910e+09,1.455001e+09,92.700000,84.900000,500.000000,8.062377e+08,3.557635e+08,2.805985e+08,9054.500000,2.000000,...,3.000000,90.800000,97.900000,68.000000,752.250000,705.500000,1.455001e+09,1.245747e+08,-4.200000,11.500000
max,2.967610e+09,3.305318e+09,100.000000,100.000000,1598.000000,2.063720e+09,9.271419e+08,9.333857e+08,11993.000000,6.000000,...,9.000000,100.000000,100.000000,137.000000,1029.000000,898.000000,3.305318e+09,4.629823e+08,19.300000,22.870000

In [22]:
# save dataframe as a csv file for further use in powerbi or anywhere

data.to_csv(
    "Construction_data.csv",
    index=False
)